#! /bin/sh

#polybar
 /usr/bin/polybar &

#start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

#notifications
dunst &

#tap to click
xinput set-prop 14 338 1 &

#wallpaper
feh --bg-scale ~/Pictures/old.png &

bspc monitor -d 1 2 3 4 5 

bspc config normal_border_color "#1e1e2e"
bspc config active_border_color "#1e1e2e"
bspc config focused_border_color "#cba6f7"
#bspc config presel-feedback_color "#1e1e2e"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

